### ISSUE TITLE
Consider opening pull request against upstream / release as new npm package

### ISSUE THREAD

**Issue by fed135** [d3m3vilurr/node-lru-native#3]
Hello, I've looked at all the forks from the original project (https://github.com/adzerk/node-lru-native) and yours seems to be the most stable one that has support for OSX and node 10.

So that people don't have to point to dig to find a good version and don't need to install via a github hash, would you consider opening a pull request against the upstream or alternatively, release this as a new npm package?

Thank you!

**Comment by d3m3vilurr** [comment]
@fed135 Hi.

adzerk/node-lru-native#8 didn't allow the patch in this repo. (and I'm not sure that repo is still alive)
kibae/node-lru-native#1 @kibae didn't maintain his repo.
so yes, I can publish my repo, but I have no idea for good name.
can you suggest anyone? I don't want `lru-native3`. :'(

**Comment by d3m3vilurr** [comment]
@ltetzlaff already taken `lru-native3` :p

short review
pros:
- contain osx patch
- contain typescript definition

cons:
- missing windows patch
- missing CI check

**Comment by fed135** [comment]
I believe that the original repo is active again, @micha posted a new branch 16 hours ago.

**Comment by fed135** [comment]
Opening pull requests should be functional: [test](https://github.com/adzerk/node-lru-native/compare/master...d3m3vilurr:master)

...might just want to consider changing back from `lru-native2` to `node-lru-native` ;)

**Comment by micha** [comment]
Hi @fed135, sorry I've been remiss lately.

**Comment by micha** [comment]
I'd be open to discussing how we can move the original repo forward.

**Comment by d3m3vilurr** [comment]
@fed135 master tree would be easy. it just need to revert package.json changes.
but I removed coffee script part just my prefer. it couldn't be allowed in original repo.
@micha right? ;)
if @micha would receive all of patchset, I'm glad to make the pr :)

(anyway I also see the new branch, but I don't understand why you add docker related files?)

**Comment by micha** [comment]
@d3m3vilurr The docker files are to have a stable build environment for node v5.x. I am not married to coffeescript but I need to maintain support for older node versions for now.

**Comment by micha** [comment]
I would also like to avoid introducing breaking changes (eg. updating timestamp when value is retrieved from cache) if possible. We could add new methods for these new behaviors instead of changing the existing behavior.

**Comment by d3m3vilurr** [comment]
well, easy way is just add to number into `.travis.yml`. CI can check the compatibility

**Comment by micha** [comment]
Sounds good to me, I can remove the docker stuff. There were a few feature request issues that I would like to implement:

* Optionally specify TTL per item when the item is added to the cache.
* Optionally reset TTL when item is retrieved from the cache.
* Optionally not reset recency when item is added to or retrieved from the cache.
* Optionally not reset TTL when item is added to the cache (and respect per-object TTLs as above).

Are there more? Want to think about a good API without introducing breaking changes.

**Comment by d3m3vilurr** [comment]
well..
first, I just simple Ci test with branch. and I got the some problem.
node 4~5 is quite old, and didn't support modern javascript.
maybe you should split the version for old javascript then remain it rest in peace.

second @kibae 's change is only different of the original repo.
so imo, this repo doesn't have any breaking changes yet.
but your requirements are pretty new features. imo, it's another job. :/

**Comment by d3m3vilurr** [comment]
here is [CI](https://travis-ci.org/d3m3vilurr/node-lru-native/builds/515826531) and [diff](
https://github.com/d3m3vilurr/node-lru-native/compare/master..check-old-version-nodes) to support old version nodes.
we just have problem in osx, but it related old version node-gyp.

**Comment by micha** [comment]
I'd prefer not to maintain forks for different versions of node, is this a pipe dream? I know there has been a lot of churn in the node ecosystem especially with the latest LTR version.

My priorities for the project are as follows:

1. Correctness
2. Performance
3. Stability
4. Features
5. Support for latest version of nodejs.
6. Support for non-Linux platforms.

**Comment by d3m3vilurr** [comment]
I agree most part. and 1~3 points are the reason why my team use this module. :)
(and specially I like the 6. cuz I don't have non-linux platform)

Just I mean, node 4 [was stopped](https://github.com/nodejs/Release#end-of-life-releases) LTS already.

I was started node 0.6(or 0.8) and serviced with node v4 in working place.
And some projects are still using it.(not my team ;p)
but I only have the memory that old node version(include v4) was unstable.
(it's just personal experience & memory)

and I can understand why you maintain it for old node version. because I also do that for old projects.. :(

**Comment by micha** [comment]
We still have one service on node v5.12.0 that I need to support for a little while yet. That being said, I am of course in favor of keeping the library up to date and usable on all newer LTS versions, as well. Hopefully there is a way we can achieve this without too much complexity.

My thinking with respect to non-Linux platforms is that this library is really aimed at high volume webserver applications, which will always be Linux. Things can get complex when you try to support the quirks of every platform.

**Comment by d3m3vilurr** [comment]
yes. and I remained wrong comment. I don't like to support every platform, and it's very stressful.
(and sometimes, support linux is also same, for example `node-ffi` didn't support alpine linux. I made patch at 3yr ago, it doesn't merge yet.)

but sometimes I need to support my coworkers. someone only use windows and someone blamed me that this project didn't support osx :p
(@fed135 also want stable osx supporting version)

anyway this project is pretty small and only problem is `NaN` part.
sometimes `NaN` also has changed but most time it would give to backward compatibility with small maintain cost.

**Comment by fed135** [comment]
I'm not attached to OSX support. If it's too much trouble, feel free to drop it.

**Comment by ltetzlaff** [comment]
> @ltetzlaff already taken `lru-native3` :p
> 
> short review
> pros:
> 
> * contain osx patch
> * contain typescript definition
> 
> cons:
> 
> * missing windows patch
> * missing CI check

Hi there 👋

Wasn't aware of this fork here, I've just recently picked this module up and decided I'd want to maintain it for use in some of my projects, just this morning I added basic CI and next up is support to be used through Docker containers running `node-alpine`.

What I'm not planning though is Node version < 8 but would be looking forward to a Windows-targeted PR. Should we bundle our endeavors in this regard (i.e. work on one repo / upstream as suggested)?

Cheers 🎉

**Comment by d3m3vilurr** [comment]
hi.

@fed135 my code has published in `lru_native2@1.1.0`. and still I can make the pr to original repo.

@micha if you don't want to support another platforms, it's nothing changed as adzerk#8 so just merge that, and we can handle new api or increase stability it later.
but I don't have a motivation yet, because our team have used it quite enough.

@ltetzlaff hi. actually I want to support LTS versions, just v6 was dropped node-gyp problem.(but it will end of life at last this month)
we already told that supporting every version&platform is pretty annoying.
you can pick 933364e8 to support windows system, I remember it works at 2017/06. but I don't have the windows dev system, so I don't know now.
maybe we need to setup appveyor ;)
